# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nlq < Formula
  desc "Natural-language databases — talk to your data, ship without a backend."
  homepage "https://nlqdb.com"
  version "0.1.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.20/nlq_0.1.20_macOS_x86_64.tar.gz"
      sha256 "9804eed58fbfb53cc535c320cbdebb1cf35fcc4bd570ed1a0fbd7657fdb05b99"

      define_method(:install) do
        bin.install "nlq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.20/nlq_0.1.20_macOS_arm64.tar.gz"
      sha256 "a67da0d710f0fd6c542b8f07b283666119447c9ccd64a5c5e72937fa8ab19870"

      define_method(:install) do
        bin.install "nlq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.20/nlq_0.1.20_linux_x86_64.tar.gz"
      sha256 "0c7db3b7dd77a83016ad9667232adc594e8fb8a6eb8e7afafb3a0e3d8fbc6df8"
      define_method(:install) do
        bin.install "nlq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.20/nlq_0.1.20_linux_arm64.tar.gz"
      sha256 "b6121cdc2284c49b52249d1c94bc4684292dab77e5bdc85eca046711f599f8d4"
      define_method(:install) do
        bin.install "nlq"
      end
    end
  end

  test do
    system "#{bin}/nlq", "--version"
  end
end
