# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nlq < Formula
  desc "Natural-language databases — talk to your data, ship without a backend."
  homepage "https://nlqdb.com"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.12/nlq_0.1.12_macOS_x86_64.tar.gz"
      sha256 "42c2aed96eecf9467a875e294937450529fd33cf08278b0f3a7431694d7faebc"

      define_method(:install) do
        bin.install "nlq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.12/nlq_0.1.12_macOS_arm64.tar.gz"
      sha256 "0d8c51464e05fb86ee323f86e10a68b9a4f422319b603d2a2531b9ec88b0f05c"

      define_method(:install) do
        bin.install "nlq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.12/nlq_0.1.12_linux_x86_64.tar.gz"
      sha256 "63a9266603b3081034cffd25351751566ce39cc2800e53a5754d1030b704814a"
      define_method(:install) do
        bin.install "nlq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.12/nlq_0.1.12_linux_arm64.tar.gz"
      sha256 "d08258042489cc8b243f6300915301f8f9717c3eba00f5c8b6651a2141886e62"
      define_method(:install) do
        bin.install "nlq"
      end
    end
  end

  test do
    system "#{bin}/nlq", "--version"
  end
end
