# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nlq < Formula
  desc "Natural-language databases — talk to your data, ship without a backend."
  homepage "https://nlqdb.com"
  version "0.1.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.19/nlq_0.1.19_macOS_x86_64.tar.gz"
      sha256 "c3032b5a83cbd3c032b318591e7f9ee47ec2227e665bb5cdbc75811a1fc199a4"

      define_method(:install) do
        bin.install "nlq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.19/nlq_0.1.19_macOS_arm64.tar.gz"
      sha256 "e265b3a248061e0c6420c7e3c914e30bb09680706c0deee501658a180a505269"

      define_method(:install) do
        bin.install "nlq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.19/nlq_0.1.19_linux_x86_64.tar.gz"
      sha256 "9480fe313d3d50f1561dd78c3f53249db11c6fc7da0ef3d741aef523ac2c1a85"
      define_method(:install) do
        bin.install "nlq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nlqdb/nlqdb/releases/download/v0.1.19/nlq_0.1.19_linux_arm64.tar.gz"
      sha256 "5c0f5f9f2530ddcf5609d9cc31150c1768a68d8f4169c6b7592e14c91eda9645"
      define_method(:install) do
        bin.install "nlq"
      end
    end
  end

  test do
    system "#{bin}/nlq", "--version"
  end
end
